config/routes.rb
Chat::Application.routes.draw do

  resources :users
  resources :tweets do
      resources :comments
  end

  resources "login", :only=>["index"]
  match 'login' => 'login#login'

    root :to => 'login#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    has_many:comments, :dependent => :destroy

    validates :user , :presence => true
    validates :tweet, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @tweet = Tweet.find(params[:tweet_id])
        @comment = Tweet.find(params[:tweet_id]).comments.create(params[:comment])
        @comment.user = @tweet.user
        redirect_to tweets_path(@tweet)
    end

    def destroy
        @comment = Comment.find(params[:id])
        @comment.destroy
        render json: {comment: @comment}
    end

end

app/controllers/login_controller.rb
#encoding:utf-8

class LoginController < ApplicationController

    def index
       @login_user = User.new
    end

    def login
        _user = params[:user]
        is_user = User.find(:first, :conditions=>[ "mail=? and password=?", _user[:mail], _user[:password]])
        if is_user != nil
            _user.delete('password')
            _user[:firstname] = is_user[:firstname]
            _user[:lastname] = is_user[:lastname]
            session[:user] = _user
            redirect_to '/tweets'
        else
            #@login_user = User.new
            #@login_user.mail = _user['mail']
            msg = 'メールアドレスかパスワードが間違っています。'
            redirect_to root_path, notice: msg
        end
    end
end

app/controllers/tweets_controller.rb
#encoding:utf-8
class TweetsController < ApplicationController

	def index
		@tweets = Tweet.all(:order =>'created_at DESC')
        @new_tweet = Tweet.new
        _user = session[:user]
        _user_name = _user[:lastname] + ' ' + _user[:firstname]
        @new_tweet.user = _user_name
        @comment = Comment.new
        @comment.user = _user_name
	end

	def new
		@tweet = Tweet.new
	end
	
	def create
		@new_tweet = Tweet.new(params[:tweet])
		@new_tweet.save
        #render json: { tweet: @new_tweet }
        redirect_to tweets_path
    end
    
    def destroy
        @tweet = Tweet.find(params[:id])
        @tweet.destroy
        render json: { tweet: @tweet }
    end

    def show
        @tweet = Tweet.find(params[:id])
    end

    def edit
        @tweet = Tweet.find(params[:id])
    end

    def update
        @tweet = Tweet.find(params[:id])
        if @tweet.update_attributes(params[:tweet])
            redirect_to tweets_path, notice: '「' + @tweet.user +
                '」さん のつぶやきがねつ造されました。'
            else
            render action: 'edit'
        end
    end
end

app/controllers/users_controller.rb
#encoding:utf-8

class UsersController < ApplicationController

    def index
        @user = User.new
    end

    def create
        @user = User.new(params[:user])
        @user[:is_valid] = 'false'
        if @user.save
           redirect_to '/'
        else
            redirect_to '/', notice: '登録処理に失敗しました。'
        end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
#encoding:utf-8
<!DOCTYPE html>
<html>
<head>
  <title>Chat</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'ogi_favicon.png' %>
</head>
<body>

<div class="header">
    <table>
    <tr>
        <td width="1%">&nbsp;</td>
        <td><%= image_tag("rails.png") %></td>
        <td width="100%">
            <div class="chat_title">　Railsでチャット</div>
            <div class="chat_link">
                <%= link_to 'ログイン', root_path %>
                <%= link_to 'ヘルプ', root_path %>
            </div>
        </td>
    </tr>
    </table>
</div>

<div class="main">
<%= yield %>
</div>

</body>
</html>

app/views/login/index.html.erb
#encoding:utf-8

<br>
<% if flash[:notice] %>
  <div id="notice"><%= image_tag("warning.jpg") %><%= notice %></div>
<% end %>
<br>


<%= form_for @login_user, :url =>{:action =>'login'} do |f| %>
<table style="margin-left: auto;margin-right: auto;">
<tr>
    <th><%= f.label :mail, 'メールアドレス' %></th>
    <td><%= f.text_field :mail %></td>
</tr>
<tr>
    <th><%= f.label :password, 'パスワード' %></th>
    <td><%= f.password_field :password %></td>
</tr>
</table>

<%= f.hidden_field :lastname %>
<%= f.hidden_field :firstname %>
<%= f.submit 'ログイン' %>
<% end %>

app/views/tweets/edit.html.erb
#encoding:utf-8
<h2>つぶやきをねつ造します。</h2>

<%= form_for @tweet do |f| %>

<div class="field">
  <%= f.hidden_field :user %>
</div>

<div class="field">
  <%= f.text_area :tweet, :rows =>5 %>
</div>

<div class="actions">
  <%= f.submit 'ねつ造する' %>
</div>
<% end %>

app/views/tweets/index.html.erb
#encoding:utf-8

<br>
<% if flash[:notice] %>
    <div id="notice"><%= image_tag("warning.jpg") %><%= notice %></div>
<% end %>
<br>

<%= form_for @new_tweet do |f| %>

<table style="margin-left: auto;margin-right: auto;">
<tr>
    <td><%= f.hidden_field :user %></td>
    <td><%= f.text_area :tweet, :rows =>3 %></td>
    <td><%= f.submit 'つぶやく' %></td>
</tr>
</table>
<% end %>

<br>
<hr width="45%">
<br>
<br>


<div class="display">
<table id="tweet_table">
  <% @tweets.each do |tweet| %>
  <tr id="tweet_<%= tweet.id %>">
    <td>
      <div class="user"><%= tweet.user %></div><br>
      <div class="tweet"><pre><%= tweet.tweet %></pre></div><br>
      <div class="tweet_action">
        <a href="javascript:void(0)" onclick="comment_display(<%= tweet.id %>)">コメント</a>
        <%= link_to '削除する', tweet, :method => :delete, :confirm => '本当に削除しますか？', :remote => true%>
        <%= link_to 'ねつ造する', edit_tweet_path(tweet) %>
        投稿日：<%= tweet.created_at %>
      </div><br>
    </td>
  <tr>
  <tr id="comment_summary_<%= tweet.id %>">
    <% if tweet.comments.any? %>
    <td><div class="comment_summary">
      <a href="javascript:void(0)" onclick="comment_display(<%= tweet.id %>)">コメント<%= tweet.comments.length %>件</a>
    </div></td>
    <% end %>
  </tr>
  <tr id="comment_<%= tweet.id %>" style="display:none">
    <td>
        <% if tweet.comments.any? %>
          <table id="comment_table">
          <% tweet.comments.each do |comment| %>
            <tr>
              <td>
                <div class="user"><%= comment.user %></div><br>
                <pre><%= comment.body %></pre><br>
                <div class="tweet_action">投稿日：<%= comment.created_at %></div>
              </td>
            </tr>
            <tr><td><hr></td></tr>
          <% end %>
          </table>
        <% end %>
        <table id="comment_table">
        <tr><td>
        <%= form_for([tweet, @comment]) do |f| %>
          <%= f.hidden_field :user %>
          <%= f.text_area :body, :rows =>3 %>
          <%= f.submit 'コメント' %>
        <% end %>
        </tr></td>
        </table>      
    </td>
  </tr>
  <tr id="delimiter_<%= tweet.id %>"><td><hr></td></tr>
  <% end %>
</table>
</div>


<script>
$(function(){

  setTimeout(function(){
    $('#notice').fadeOut("slow");
  }, 2500);

  $('a[data-method="delete"]').on('ajax:success', function(e, data, status, xhr) {
    $('#tweet_'+data.tweet.id).fadeOut("slow");
    $('#comment_'+data.tweet.id).fadeOut("slow");
    $('#comment_summary_'+data.tweet.id).fadeOut("slow");
    $('#delimiter_'+data.tweet.id).fadeOut("slow");
  });

});

function comment_display(id){
    $('#comment_'+id).fadeIn(1000);
}
</script>

app/views/users/index.html.erb
#encoding:utf-8

<%= form_for @user do |f| %>
<table style="margin-left: auto;margin-right: auto;">
<tr>
    <th><%= f.label :lastname %></th>
    <td><%= f.text_field :lastname %></td>
</tr>
<tr>
    <th><%= f.label :firstname %></th>
    <td><%= f.text_field :firstname %></td>
</tr>
<tr>
    <th><%= f.label :mail %></th>
    <td><%= f.text_field :mail %></td>
</tr>
<tr>
    <th><%= f.label :password %></th>
    <td><%= f.password_field :password %></td>
</tr>
</table>

<%= f.hidden_field :is_valid %>
<%= f.submit '登録' %>
<% end %>